name: CI - frontend

on:
  push:
    branches: ['main']
    paths:
      - 'frontend/**'
  pull_request:
    branches: ['main']
    paths:
      - 'frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run Linter
        run: |
          cd frontend
          npm run lint

      - name: Run Tests
        run: |
          cd frontend
          npm run test
        env:
          VITE_SERVICE_URL: ${{ secrets.VITE_SERVICE_URL }}

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy to Render
        run: curl https://api.render.com/deploy/srv-d0itlvadbo4c738s8ggg?key=AWQf1fZ8Xs0
